# Generated by Django 4.2.16 on 2024-10-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profileing',
            new_name='profileimg',
        ),
    ]
