# Generated by Django 4.2.16 on 2024-10-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_profileing_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(blank=True, default='profile_images/default.jpg', null=True, upload_to='profile_images'),
        ),
    ]
