# Generated by Django 4.2.16 on 2024-10-12 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_likepost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
